apiVersion: v1
kind: Service
metadata:
  name: <app-name>-service
  namespace: {{ .Values.Namespace }} 
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: <app-name>-service
