apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
- ../../base

namePrefix: dev-

commonLabels:
  environment: dev

replicas:
- name: demo-api
  count: 2

patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: <ACR_NAME>.azurecr.io/demo-api:latest-dev
    - op: replace
      path: /spec/template/spec/containers/0/env/1/value
      value: dev
  target:
    kind: Deployment
    name: demo-api

- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: demo-api-dev.example.com
  target:
    kind: Ingress
    name: demo-api
